repos:
  - repo: https://github.com/psf/black
    rev: 26.5.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 9.0.0a3
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: |
          (?x)(
              ^.+\.spec|
              ^.+\.dat|
              ^.+\.levels
          )
      - id: trailing-whitespace
        exclude: |
          (?x)(
              ^.+\.spec|
              ^.+\.dat|
              ^.+\.levels
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)(
              ^.+\.spec|
              ^.+\.dat|
              ^.+\.levels
          )
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: debug-statements
