# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"  # Changed from mambaforge to standard Python 3.8 (more stable)

python:
  install:
    - method: pip
      path: .
      extra_requirements: [docs]
      use_venv: true  # Isolated environment

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false  # Temporarily disable to identify real errors

# Removed sections:
# - conda: environment.yml (causes conflicts)
# - apt_packages: mesa-vulkan-drivers (not needed for docs)
# - formats: pdf/epub (simplify initial build)
