# .readthedocs.yml
# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    #According to error message: Expected one of (2.7, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, miniconda3-4.7, miniconda3-3.12-24.1, miniconda3-3.12-24.9, mambaforge-4.10, mambaforge-22.9, mambaforge-23.11, 3, latest, miniconda-latest, mambaforge-latest), got type str (miniforge3-23.11).
    python: "3.12"
    # Use Mambaforge as the environment manager
    # (this replaces the default CPython/venv)
    mambaforge: latest
  apt_packages:
    - mesa-vulkan-drivers #for running GPU examples
    - libvulkan1          #for running GPU examples

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
  # You can configure Sphinx to use a different builder, for instance use the dirhtml builder for simpler URLs
  # builder: "dirhtml"
  # Fail on all warnings to avoid broken references
  # fail_on_warning: true

# Optionally build your docs in additional formats such as PDF and ePub
#formats:
#    - pdf
#    - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
      - docs      #  ReadTheDocs will install Radis with "pip install .[docs]" so extra packages are read from setup.py ["docs":....]

conda:
  environment: environment.yml
