codecov:
  notify:
    # Do not wait for CI to pass before sending the Codecov status/comment
    # Travis CI doesn't run on forks natively, so waiting causes Codecov to hang forever.
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"

  ignore:
    - "radis/test/**"

  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 1%
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  # Force Codecov to post a comment on the PR even if coverage did not change
  require_changes: no
