# -*- coding: utf-8 -*-
"""Tools : database of spectra, line survey."""

import importlib

__all__ = [
    "SpecDatabase",
    "load_spec",
    "plot_spec",
    "save",
    "get_eq_mole_fraction",
    "plot_slit",
    "get_effective_FWHM",
    "get_FWHM",
]

# Generated by AI in #842 to avoid circular imports and to lazy load submodules only when needed.
_EXPORT_TO_MODULE = {
    "SpecDatabase": "database",
    "load_spec": "database",
    "plot_spec": "database",
    "save": "database",
    "get_eq_mole_fraction": "gascomp",
    "plot_slit": "slit",
    "get_effective_FWHM": "slit",
    "get_FWHM": "slit",
    # Convenience exports that were previously imported eagerly.
    "convolve_with_slit": "slit",
    "crop_slit": "slit",
    "recenter_slit": "slit",
}


def _load_submodule(name):
    module = importlib.import_module(f".{name}", __name__)
    globals()[name] = module
    return module


def __getattr__(name):
    module_name = _EXPORT_TO_MODULE.get(name)
    if module_name is not None:
        module = _load_submodule(module_name)
        value = getattr(module, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")


def __dir__():
    return sorted(set(globals()) | set(__all__) | set(_EXPORT_TO_MODULE))
