name: 🚀 Feature
description: "Suggest an idea for Radis \U0001F331"
title: "🚀 Feature: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out our feature request form !!
  - type: textarea
    id: feature-description
    validations:
      required: true
    attributes:
      label: "🔖 Feature description"
      description: "A clear and concise description of what you want to happen"
      placeholder: "Please write here"
  - type: textarea
    id: Why-you-want-this-feature
    validations:
      required: false
    attributes:
      label: "👉 Why you want this feature!!"
      description: "Please explain why this feature should be implemented and how it would be used. Add examples, if applicable."
      placeholder: "In my use-case, ..."
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "👀 Have you  check if this issue has been raised before?"
      description: "Have you Googled for a similar issue ?"
      options:
        - label: "I checked and didn't find similar issue"
          required: true
  - type: checkboxes
    id: vote-here
    attributes:
      label: "Have you vote for the feature"
      options:
        - label: "I have read the [vote](https://github.com/radis/radis/issues/79)"
          required: false




