
worker_processes  1;
error_log ${GITHUB_DIR}/nginx_logs/error.log info;

events {
    worker_connections  1024;
}


http {
    #include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

	log_subrequest on;

	log_format cache_status
		'$remote_addr - $remote_user [$time_local] '
		'"$request" $status $body_bytes_sent '
		'"$http_referer" "$http_user_agent" '
		'Cache:$upstream_cache_status '
		'Range:"$slice_range" '
		'Upstream:"$upstream_addr" '
		'UpstreamStatus:"$upstream_status"';
		
	
	
    access_log ${GITHUB_DIR}/nginx_logs/access.log cache_status;
    sendfile        on;

    keepalive_timeout  65;


    proxy_cache_path ${GITHUB_DIR}/nginx_cache levels=1:2 keys_zone=download_cache:10m max_size=10g inactive=60m use_temp_path=off;

    server {
        listen       80;
        server_name  www.hitran.org hitran.org localhost;
        return 301 https://$host$request_uri; # Redirects automatically
    }

    # HTTPS server

    server {
       listen       443 ssl;
       server_name  www.hitran.org;

       ssl_certificate      cert.pem;
       ssl_certificate_key  cert.key;

       ssl_session_cache    shared:SSL:1m;
       ssl_session_timeout  5m;

       ssl_ciphers  HIGH:!aNULL:!MD5;
       ssl_prefer_server_ciphers  on;

       return 301 https://hitran.org$request_uri;
    }

    server {
       listen       443 ssl;
       server_name  hitran.org;

       ssl_certificate      cert.pem;
       ssl_certificate_key  cert.key;

       ssl_session_cache    shared:SSL:1m;
       ssl_session_timeout  5m;

       ssl_ciphers  HIGH:!aNULL:!MD5;
       ssl_prefer_server_ciphers  on;

       location / {

           # Force NGINX to bypass /etc/hosts using public DNS
           resolver 8.8.8.8 valid=300s;
           set $upstream_endpoint https://hitran.org;
           proxy_pass $upstream_endpoint;
           proxy_ssl_server_name on;
           proxy_set_header Host hitran.org;

           proxy_set_header X-Forwarded-Proto https;
           proxy_set_header X-Forwarded-Host $host;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

           proxy_cache_lock on;
           proxy_cache_lock_age 30s;

           proxy_cache download_cache;
		   proxy_ignore_headers Cache-Control Expires Set-Cookie Vary;

		   # proxy_http_version 1.1;
		   # proxy_set_header Connection "";
		   # proxy_set_header Keep-Alive "";

		   # proxy_buffer_size 128k;
		   # proxy_buffers 4 256k;

           proxy_cache_valid 200 206 1d; # Caches successful downloads for 1 day

		   proxy_cache_key $scheme$request_method$proxy_host$request_uri$slice_range;

		   slice              32m;
           # proxy_cache_key    $host$uri$is_args$args$slice_range;
           proxy_set_header   Range $slice_range;
           proxy_http_version 1.1;

           add_header X-Cache-Status $upstream_cache_status;
           add_header X-Served-By "My-Nginx-Proxy";

       }
       location /login/ {

           # Force NGINX to bypass /etc/hosts using public DNS
           resolver 8.8.8.8 valid=300s;
           set $upstream_endpoint https://hitran.org;
           proxy_pass $upstream_endpoint;
           proxy_ssl_server_name on;
           proxy_set_header Host hitran.org;

           proxy_set_header X-Forwarded-Proto https;
           proxy_set_header X-Forwarded-Host $host;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

           proxy_cache off;
       }
    }
}
