
worker_processes  1;


events {
    worker_connections  1024;
}


http {
    #include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    keepalive_timeout  65;


    proxy_cache_path /Users/runner/work/radis/radis/nginx_cache levels=1:2 keys_zone=download_cache:10m max_size=10g inactive=60m use_temp_path=off;

    server {
        listen       80;
        server_name  localhost;
        return 301 https://$host$request_uri; # Redirects automatically
    }

    # HTTPS server

    server {
       listen       443 ssl;
       server_name  www.hitran.org;

       ssl_certificate      ../../cert.pem;
       ssl_certificate_key  ../../cert.key;

       ssl_session_cache    shared:SSL:1m;
       ssl_session_timeout  5m;

       ssl_ciphers  HIGH:!aNULL:!MD5;
       ssl_prefer_server_ciphers  on;

       location / {

		   # Force NGINX to bypass /etc/hosts using public DNS
		   resolver 8.8.8.8 valid=300s;

           # Assigning to a variable forces runtime DNS resolution
           set $upstream_endpoint https://www.hitran.org;
           proxy_pass $upstream_endpoint;
		   proxy_ssl_server_name on;
		   proxy_set_header Host www.hitran.org;

		   # Only let 1 request download at a time
		   proxy_cache_lock on;

		   # If a download stalls, let another try after 5s
           #proxy_cache_lock_timeout 5s;

		   # Max time a single download is allowed to take
           proxy_cache_lock_age 30s;

           proxy_cache download_cache;

		   proxy_cache_valid 200 7d; # Caches successful downloads for 7 days

           add_header X-Cache-Status $upstream_cache_status;
           add_header X-Served-By "My-Nginx-Proxy";
       }
    }

}
