#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# RADIS documentation build configuration file
# See https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys
import sphinx_gallery.gen_rst
from sphinx_gallery.sorting import FileNameSortKey

# ================== CRITICAL RTD FIXES ==================
# Block all network calls and force CPU-only mode
os.environ['RADIS_NO_DOWNLOAD'] = '1' 
os.environ['RADIS_SKIP_ONLINE_TESTS'] = '1'
os.environ['RADIS_BACKEND'] = 'numpy'

# Mock all problematic imports (must be at top)
autodoc_mock_imports = [
    '_radis', 'astropy', 'vaex', 'joblib',
    'tables', 'h5py', 'pandas', 'numpy', 'scipy'
]
# ========================================================

# Custom Example header template
sphinx_gallery.gen_rst.EXAMPLE_HEADER = """
.. DO NOT EDIT.
.. THIS FILE WAS AUTOMATICALLY GENERATED BY SPHINX-GALLERY.
.. TO MAKE CHANGES, EDIT THE SOURCE PYTHON FILE:
.. "{0}"
.. LINE NUMBERS ARE GIVEN BELOW.

.. only:: html

    .. note::
        :class: sphx-glr-download-link-note

        You can download :ref:`below <sphx_glr_download_{1}>`
        the full example code{2} and run it with 🔬 `Radis-Lab <https://radis.github.io/radis-lab/>`__,

.. rst-class:: sphx-glr-example-title

.. _sphx_glr_{1}:

"""

# Add project to path
sys.path.insert(0, os.path.abspath(".."))

# -- General configuration ------------------------------------------------
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.mathjax",
    "sphinx.ext.autosummary",
    "sphinx_gallery.gen_gallery",
    "sphinx.ext.napoleon",
    "sphinx_autodoc_defaultargs",
    "sphinx.ext.intersphinx",
    "sphinx.ext.inheritance_diagram",
    "sphinx.ext.linkcode",
]

# Sphinx Gallery configuration
sphinx_gallery_conf = {
    "examples_dirs": "../examples",
    "gallery_dirs": "auto_examples",
    "doc_module": "radis",
    "reference_url": {"radis": None},
    "backreferences_dir": "source/backreferences",
    "doc_module": ("radis"),
    "inspect_global_variables": True,
    "show_signature": False,
    "within_subsection_order": FileNameSortKey,
    "show_memory": False,          # Reduces build load
    "min_reported_time": 5,        # Skip fast examples
}

# API doc generation
def run_apidoc(_):
    argv = [
        "-f",
        "-e",
        "-o",
        "source",
        "--separate",
        "../radis",
    ]
    from sphinx.ext import apidoc
    apidoc.main(argv)

def setup(app):
    app.connect("builder-inited", run_apidoc)
    app.add_css_file("custom.css")

# Intersphinx mapping (simplified)
intersphinx_mapping = {
    # Core dependencies (from patch-4)
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
    
    # Additional mappings (from develop branch)
    "astropy": ("https://docs.astropy.org/en/stable/", None),
    "astroquery": ("https://astroquery.readthedocs.io/en/latest/", None),
    "exojax": ("https://secondearths.sakura.ne.jp/exojax/objects.inv", None),
    "fitroom": ("https://fitroom.readthedocs.io/en/latest/", None),
    "habanero": ("https://habanero.readthedocs.io/en/latest/", None),
    "joblib": ("https://joblib.readthedocs.io/en/latest/", None),
    "lmfit": ("https://lmfit.github.io/lmfit-py/", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable/", None),
    "pytexit": ("https://pytexit.readthedocs.io/en/latest/", None),
    "seaborn": ("https://seaborn.pydata.org/", None),
    "specutils": ("https://specutils.readthedocs.io/en/stable/", None),
    "vaex": ("https://vaex.readthedocs.io/en/latest/", None),
}

# Napoleon settings
napoleon_google_docstring = False
napoleon_use_param = False

# Project information
project = 'RADIS'
copyright = '2023, RADIS contributors'
author = 'Erwan Pannier et al.'

# Version info
with open("../radis/__version__.txt") as f:
    release = f.read().strip()
version = release

# -- Options for HTML output ----------------------------------------------
html_theme = 'alabaster'
html_theme_options = {
    "description": "Radiative Solver",
    "logo_name": True,
    "github_user": "radis",
    "github_repo": "radis",
    "github_button": True,
    "fixed_sidebar": True,
    "extra_nav_links": {
        "RADIS Website": "https://radis.github.io/",
        "Video Tutorials": "https://www.youtube.com/channel/UCO-7NXkubTAiGGxXmvtQlsA",
    },
}
html_static_path = ['_static']
html_sidebars = {
    "**": [
        "about.html",
        "navigation.html",
        "searchbox.html",
        "buttons.html",
    ]
}

# -- Options for LaTeX output ---------------------------------------------
latex_elements = {
    'preamble': r'\setcounter{tocdepth}{3}',
}
