# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests on develop

on:
  push:
    branches: [ "develop" ] #see python-package-master.yml for tests on master
  pull_request:
    branches: [ "develop" ]

jobs:
  pre-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Github cache download
        uses: actions/cache@v4
        with:
          path: |
            nginx_cache
          # Using a unique run key, this first job will always miss the cache, re-download, and store the new cache
          key: hitran-cache-${{ github.run_id }}-${{ github.run_attempt }}
          enableCrossOsArchive: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest specutils
          pip install -e .

      - &setup_proxy_linux
        name: Set-up proxy server (Linux)
        if: runner.os == 'Linux'
        run: | # generate SSL certificates, run server in the background, and reroute hitran traffic to the proxy
            openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/CN=www.hitran.org" -keyout cert.key -out cert.pem -addext "subjectAltName = DNS:www.hitran.org,DNS:hitran.org,DNS:localhost,IP:127.0.0.1"

            export NGINX_CACHE_DIR=/home/runner/work/radis/radis/nginx_cache
            envsubst '$NGINX_CACHE_DIR' < .github/proxy/nginx.conf > .github/proxy/nginx.conf.gen
            sudo nginx -c $GITHUB_WORKSPACE/.github/proxy/nginx.conf.gen -g "user $(whoami);"& 

            echo "127.0.0.1 www.hitran.org  hitran.org" | sudo tee -a /etc/hosts

            sudo cp "$GITHUB_WORKSPACE/cert.pem" /usr/local/share/ca-certificates/nginx-proxy.crt
            sudo update-ca-certificates
            echo "REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt" >> $GITHUB_ENV

      - name: Test Proxy
        run: |
          pip install requests urllib3
          python .github/proxy/test_proxy.py pre-build

      - name: Connection required tests with pytest
        env:
          HITRAN_EMAIL: ${{ secrets.HITRAN_EMAIL }}
          HITRAN_PASSWORD: ${{ secrets.HITRAN_PASSWORD }}
        run: |
          echo ${{ secrets.HITRAN_EMAIL && 'HITRAN credentials available!' || 'HITRAN credentials NOT available!' }}
          pytest -s radis/test/io/test_exomol.py::test_calc_exomol_vs_hitemp
        #  pytest -m "needs_connection and not download_large_databases and not needs_fixing ${{ secrets.HITRAN_EMAIL && ' ' || 'and not needs_HITRAN_credentials' }}" --durations=10 --tb=short


  build:
    env:
      MPLBACKEND: Agg
    strategy:
      fail-fast: false
      # max-parallel: 3
      matrix:
        include:
          # Try only the oldest and latest supported versions of Python on develop, to speed up the tests. We test more versions on master (see python-package-master.yml)
          - os: ubuntu-latest
            python-version: "3.10"
          - os: ubuntu-latest
            python-version: "3.12"
          - os: ubuntu-latest
            python-version: "3.13" #added to test the behavior without vaex (compatible up to 3.12)
          #For windows and macOS, we test only the Python 3.12, to speed up the tests.
          - os: windows-latest
            python-version: "3.12"
          - os: macos-latest
            python-version: "3.12"
    runs-on: ${{ matrix.os }}

    needs: pre-build # Forces completion of the downloads & caching first

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Github cache download
        uses: actions/cache@v4
        with:
          path: |
            nginx_cache
          key: hitran-cache-${{ github.run_id }}-${{ github.run_attempt }}
          enableCrossOsArchive: true
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest specutils pytest-cov
          pip install -e .
          
      - *setup_proxy_linux
      - name: Set-up proxy server (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: | # generate SSL certificates, run server in the background, and reroute hitran traffic to the proxy
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/CN=www.hitran.org" -keyout cert.key -out cert.pem -addext "subjectAltName = DNS:www.hitran.org,DNS:hitran.org,DNS:localhost,IP:127.0.0.1"

          cd C:\tools\nginx-*\
          Stop-Service -Name "W3SVC" -Force
          $env:NGINX_CACHE_DIR = "D:/a/radis/radis/nginx_cache"
          (Get-Content ${{ github.workspace }}/.github/proxy/nginx.conf) -replace '\$\{NGINX_CACHE_DIR\}', $env:NGINX_CACHE_DIR | Set-Content ${{ github.workspace }}/.github/proxy/nginx.conf.gen
          Start-Process ".\nginx.exe" -ArgumentList "-c", "${{ github.workspace }}/.github/proxy/nginx.conf.gen"
          cd ${{ github.workspace }}

          Add-Content -Path C:\Windows\System32\drivers\etc\hosts -Value "`r`n127.0.0.1 www.hitran.org hitran.org"

          Import-Certificate -FilePath .\cert.pem -CertStoreLocation Cert:\LocalMachine\Root
          Copy-Item -Path .\cert.pem -Destination "${{ github.workspace }}/combined_cacert.pem"

          pip install certifi
          $pythonCertPath = python -c "import certifi; print(certifi.where())"
          Get-Content -Path $pythonCertPath | Add-Content -Path "${{ github.workspace }}/combined_cacert.pem"

          "REQUESTS_CA_BUNDLE=${{ github.workspace }}/combined_cacert.pem" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

          Get-Process nginx
      - name: Set-up proxy server (MacOS)
        if: runner.os == 'macOS'
        run: |
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/CN=www.hitran.org" -keyout cert.key -out cert.pem -addext "subjectAltName = DNS:www.hitran.org,DNS:hitran.org,DNS:localhost,IP:127.0.0.1"

          brew install nginx
          export NGINX_CACHE_DIR=/Users/runner/work/radis/radis/nginx_cache
          envsubst '$NGINX_CACHE_DIR' < .github/proxy/nginx.conf > .github/proxy/nginx.conf.gen
          sudo nginx -c ${{ github.workspace }}/.github/proxy/nginx.conf.gen -g "user $(whoami) staff;"&

          echo "127.0.0.1 www.hitran.org hitran.org" | sudo tee -a /etc/hosts

          sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain cert.pem

          python3 -c "import certifi; print(certifi.where())" > certifi_path.txt
          cp $(cat certifi_path.txt) combined_ca.pem
          cat cert.pem >> combined_ca.pem

          echo "REQUESTS_CA_BUNDLE=${{ github.workspace }}/combined_ca.pem" >> $GITHUB_ENV
          echo "SSL_CERT_FILE=${{ github.workspace }}/combined_ca.pem" >> $GITHUB_ENV

      # - name: Setup tmate session
        # uses: mxschmitt/action-tmate@v3
      - name: Test Proxy
        run: |
          pip install requests
          python .github/proxy/test_proxy.py

      - name: Fast tests with pytest
        env:
          HITRAN_EMAIL: ${{ secrets.HITRAN_EMAIL }}
          HITRAN_PASSWORD: ${{ secrets.HITRAN_PASSWORD }}
        run: |
          echo ${{ secrets.HITRAN_EMAIL && 'HITRAN credentials available!' || 'HITRAN credentials NOT available!' }}
          pytest -s radis/test/io/test_exomol.py::test_calc_exomol_vs_hitemp
        #  pytest -m     "fast and not needs_gpu and not needs_db_CDSD_HITEMP_PCN and not needs_db_CDSD_HITEMP and not needs_db_CDSD_HITEMP_PC ${{ secrets.HITRAN_EMAIL && '' || 'and not needs_HITRAN_credentials' }}" --durations=10 --cov=radis --cov-config=setup.cfg --cov-report=xml:coverage.xml
      
      # - name: Long tests with pytest
        # if: always()
        # env:
          # HITRAN_EMAIL: ${{ secrets.HITRAN_EMAIL }}
          # HITRAN_PASSWORD: ${{ secrets.HITRAN_PASSWORD }}
        # run: |
          # echo ${{ secrets.HITRAN_EMAIL && 'HITRAN credentials available!' || 'HITRAN credentials NOT available!' }}
          # pytest -m "not fast and not needs_gpu and not needs_db_CDSD_HITEMP_PCN and not needs_db_CDSD_HITEMP and not needs_db_CDSD_HITEMP_PC ${{ secrets.HITRAN_EMAIL && '' || 'and not needs_HITRAN_credentials' }} and not needs_db_HITEMP_CO2_DUNHAM and not needs_db_HITEMP_CO_DUNHAM and not download_large_databases" --durations=10 --cov=radis --cov-config=setup.cfg --cov-report=xml:coverage.xml --cov-append
      
      # - name: Upload coverage to Codecov
        # uses: codecov/codecov-action@v4
        # if: always()
        # with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          # slug: radis/radis
          # files: ./coverage.xml
          # flags: unittests
          # name: codecov-umbrella
          # fail_ci_if_error: false
